services:
  # Backend Go Web Service
  - type: web
    name: ruivobarber-backend
    runtime: docker
    autoDeploy: true
    rootDir: backend
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: ruivobarber-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ruivobarber-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: ruivobarber-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ruivobarber-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: ruivobarber-db
          property: database
      - key: DB_SSLMODE
        value: require
      - key: JWT_SECRET
        generateValue: true
      - key: TZ
        value: America/Sao_Paulo
      - key: GOOGLE_CLIENT_ID
        value: 875304695392-ps6bpdh818gs2dirgd7eqea3omvrggdb.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  # Frontend React Static Site
  - type: web
    name: ruivobarber-frontend
    runtime: static
    autoDeploy: true
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://ruivobarber-backend.onrender.com/api/v1
      - key: VITE_GOOGLE_CLIENT_ID
        value: 875304695392-ps6bpdh818gs2dirgd7eqea3omvrggdb.apps.googleusercontent.com

databases:
  - name: ruivobarber-db
    plan: free
    databaseName: ruivobarber
    user: ruivobarber_user
